name: Docker Image CI

on:
  push:
    branches:
      - deploy2

jobs:

  build:

    runs-on: ubuntu-latest

    # Set the working directory for all steps in this job
    defaults:
      run:
        working-directory: RefferalLinksBackEnd

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile -t maynghien/referallinkapi

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p '${{ secrets.DOCKER_PASSWORD }}'

    - name: Push Docker image
      run: docker push maynghien/referallinkapi
  deploy:
    needs: build
    runs-on: ubuntu-latest
  
    steps:
      - name: Install sshpass
        run: sudo apt-get install -y sshpass
  
      - name: SSH to server and pull
        run: |
          sshpass -p "${{ secrets.VPS_PASSWORD }}" ssh -o StrictHostKeyChecking=no root@maynghien.ddns.net "
            docker stop referallinkapi;
            docker system prune -af;
            docker pull maynghien/referallinkapi;
            docker run --name referallinkapi -e ASPNETCORE_ENVIRONMENT=Development -p 5001:5000 -d maynghien/referallinkapi;
            docker network connect nginx-proxy referallinkapi;
             docker restart nginx-proxy;
             docker exec referallinkapi ls /app;
             
             docker logs referallinkapi;
          "